name: Daily Countdown Email

on:
  schedule:
    # Runs at 9:00 AM UTC every day
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  send-countdown-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Calculate days remaining and select gif
      id: countdown
      run: |
        TARGET_DATE="2025-09-10"
        CURRENT_DATE=$(date +%s)
        TARGET_TIMESTAMP=$(date -d "$TARGET_DATE" +%s)
        DAYS_REMAINING=$(( ($TARGET_TIMESTAMP - $CURRENT_DATE) / 86400 ))
        echo "days=$DAYS_REMAINING" >> $GITHUB_OUTPUT
        echo "Days remaining: $DAYS_REMAINING"
        
        if [ $DAYS_REMAINING -le 0 ]; then
          echo "Target date reached!"
          echo "should_send=false" >> $GITHUB_OUTPUT
        else
          echo "should_send=true" >> $GITHUB_OUTPUT
        fi
        
        # Array of gif URLs
        GIFS=(
          "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDhtb3ZqcnlmeTgzcjdoZWJmMWExdmFpYmo5ZjFnYm91eGtsOW5iayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/qUAf5RDOPqqhsHeFAG/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDhtb3ZqcnlmeTgzcjdoZWJmMWExdmFpYmo5ZjFnYm91eGtsOW5iayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3o6Ei2yv8fqpR3nJG8/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDhtb3ZqcnlmeTgzcjdoZWJmMWExdmFpYmo5ZjFnYm91eGtsOW5iayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/13QmO3rEaDTYHD30za/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDhtb3ZqcnlmeTgzcjdoZWJmMWExdmFpYmo5ZjFnYm91eGtsOW5iayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3ohzAWPbp0ZyUpYTD2/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDhtb3ZqcnlmeTgzcjdoZWJmMWExdmFpYmo5ZjFnYm91eGtsOW5iayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/GyDsTZxIu096VWIvuf/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDhtb3ZqcnlmeTgzcjdoZWJmMWExdmFpYmo5ZjFnYm91eGtsOW5iayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3W3LJ89ofIzWKVDMBh/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3eml5ZjVmZDJqbXoxb2lrZTdhYjFzdGZ3N3E2dDR2ZDV5bGlsZmY4NSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/UP8SV1pittYn7k807k/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3aDdkdmRuN2UycTB6OTJmMjFobmMwcmlzOWo1b3BrenJ0M29xMWpkMyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/PLVIXXZUhI5GA0SVF2/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bGh4bWV3ZXluamF6cTVvdXA3bTR2bG9mcGY4aTM3aWVoYTA3aDFiaiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/STT3E1ebKKsAXMWEtH/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cWs2cmg1cmRlNXJpZDVucDFndHk3d2k4N2w5NWE5cnpuc3hnNjBhMiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/2Ka1801kZq3GjQwCVO/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3ZnU1N2F1bW1rd24yMW5weXZxbnFhNHFwcDhtMXBnOTByeWYzdmJhMiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/xT5LMSleuVuCe24KLC/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3ZXI4ajZ3MzdveWFrb2JlbWJpb3BuZG95enowcWxrdXN6aDFzNnNlcCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/2Ga8aj2mbUFK8/giphy.gif"
          "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3Z3RucHp6bnhlcDdsMDR3bjlueGp0czRxazNmdnh1djV4OHM0Ymc4NiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/rsx8QKwpSORLn974nf/giphy.gif"
        )
        
        # Select gif based on days remaining modulo array length
        ARRAY_LENGTH=${#GIFS[@]}
        GIF_INDEX=$(( $DAYS_REMAINING % $ARRAY_LENGTH ))
        SELECTED_GIF="${GIFS[$GIF_INDEX]}"
        
        echo "gif_url=$SELECTED_GIF" >> $GITHUB_OUTPUT
        echo "Selected gif index: $GIF_INDEX"
    
    - name: Send email
      if: steps.countdown.outputs.should_send == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 📅 ${{ steps.countdown.outputs.days }} days until September 10th, 2025!
        to: ${{ secrets.EMAIL_TO }}
        from: ${{ secrets.EMAIL_USERNAME }}
        # Optional: Add CC or BCC recipients
        # cc: ${{ secrets.EMAIL_CC }}
        # bcc: ${{ secrets.EMAIL_BCC }}
        html_body: |
          <!DOCTYPE html>
          <html>
          <head>
            <style>
              body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; }
              .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
              h1 { color: #333; text-align: center; }
              .countdown { background-color: #007bff; color: white; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; }
              .days { font-size: 48px; font-weight: bold; }
              .label { font-size: 24px; }
              .info { color: #666; text-align: center; margin-top: 20px; }
              .motivation { text-align: center; margin-top: 30px; }
              .motivation img { max-width: 100%; height: auto; border-radius: 8px; margin-bottom: 15px; }
              .motivation p { font-size: 20px; font-weight: bold; color: #ff4757; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Countdown to September 10th, 2025</h1>
              <div class="countdown">
                <div class="days">${{ steps.countdown.outputs.days }}</div>
                <div class="label">DAYS REMAINING</div>
              </div>
              <p class="info">
                Only ${{ steps.countdown.outputs.days }} days to go!
              </p>
              <div class="motivation">
                <img src="${{ steps.countdown.outputs.gif_url }}" alt="Daily Motivation">
                <p>Work harder Raul! 💪</p>
              </div>
            </div>
          </body>
          </html>
