name: Daily Countdown Email - Advanced

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Send test email to primary recipient only'
        required: false
        type: boolean
        default: false

jobs:
  send-countdown-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Calculate days remaining
      id: countdown
      run: |
        TARGET_DATE="2025-09-10"
        CURRENT_DATE=$(date +%s)
        TARGET_TIMESTAMP=$(date -d "$TARGET_DATE" +%s)
        DAYS_REMAINING=$(( ($TARGET_TIMESTAMP - $CURRENT_DATE) / 86400 ))
        echo "days=$DAYS_REMAINING" >> $GITHUB_OUTPUT
        echo "Days remaining: $DAYS_REMAINING"
        
        if [ $DAYS_REMAINING -le 0 ]; then
          echo "Target date reached!"
          echo "should_send=false" >> $GITHUB_OUTPUT
        else
          echo "should_send=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Determine recipients
      id: recipients
      run: |
        if [[ "${{ inputs.test_mode }}" == "true" ]]; then
          # Test mode: only send to primary recipient
          echo "to=${{ secrets.EMAIL_PRIMARY }}" >> $GITHUB_OUTPUT
          echo "cc=" >> $GITHUB_OUTPUT
          echo "bcc=" >> $GITHUB_OUTPUT
          echo "Test mode: Sending only to primary recipient"
        else
          # Normal mode: send to all recipients
          echo "to=${{ secrets.EMAIL_TO }}" >> $GITHUB_OUTPUT
          echo "cc=${{ secrets.EMAIL_CC }}" >> $GITHUB_OUTPUT
          echo "bcc=${{ secrets.EMAIL_BCC }}" >> $GITHUB_OUTPUT
          echo "Normal mode: Sending to all recipients"
        fi
    
    - name: Send email
      if: steps.countdown.outputs.should_send == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 📅 ${{ steps.countdown.outputs.days }} days until September 10th, 2025!
        to: ${{ steps.recipients.outputs.to }}
        cc: ${{ steps.recipients.outputs.cc }}
        bcc: ${{ steps.recipients.outputs.bcc }}
        from: ${{ secrets.EMAIL_USERNAME }}
        html_body: |
          <!DOCTYPE html>
          <html>
          <head>
            <style>
              body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; }
              .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
              h1 { color: #333; text-align: center; }
              .countdown { backgroun
